# Generated by Django 5.0.4 on 2025-01-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_task_list_user_delete_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_list',
            old_name='descrition',
            new_name='description',
        ),
    ]
