# Generated by Django 5.0.4 on 2025-01-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_descrition_task_list_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_list',
            old_name='description',
            new_name='taskName',
        ),
    ]
